# Generated by Django 4.0.6 on 2022-09-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0002_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
