# Generated by Django 4.0.6 on 2022-09-21 07:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category Title')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Product Heading')),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Discription')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sales')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.title')),
            ],
        ),
    ]
