# Generated by Django 4.0.6 on 2022-09-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sales')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='sales',
        ),
        migrations.AddField(
            model_name='category',
            name='total_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.totalsales'),
        ),
    ]
