# Generated by Django 4.0.6 on 2022-09-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_totalsales_remove_category_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.title'),
        ),
    ]
